[project]
name = "analysis-rt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tdinapoli", email = "tomas.dina98@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.1.2,<3",
    "scipy>=1.14.1,<2",
    "pandas>=2.2.3,<3",
    "matplotlib>=3.9.2,<4",
    "uncertainties>=3.2.2,<4",
    "openpyxl>=3.1.5,<4",
    "watchdog>=6.0.0",
]

[project.scripts]
photoacoustic = "photoacoustic.main:main"

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[tool.pixi.dependencies]
python = "==3.12"
numpy = ">=2.1.2,<3"
scipy = ">=1.14.1,<2"
pandas = ">=2.2.3,<3"
matplotlib = ">=3.9.2,<4"
uncertainties = ">=3.2.2,<4"
openpyxl = ">=3.1.5,<4"
watchdog = "*"

[tool.uv.build-backend]
module-name = "photoacoustic"
module-root = "src"

[tool.pixi.tasks]
pack = 'python tools/build_pack.py'
upload = "curl -u \"xi95ExZ8N6KWxY3:0000\" -T dist/analysis-rt-0.1.0-win-64.ps1 https://uni-muenster.sciebo.de/public.php/webdav/analysis-rt-0.1.0-win-64.ps1"
post = { depends-on=["pack", "upload"]}
sim = "python simulate_data_acq.py"